CREATE TABLE IF NOT EXISTS client_instances (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    client_name VARCHAR(190) NOT NULL,
    business_name VARCHAR(190) NOT NULL,
    domain VARCHAR(190) NOT NULL,
    city VARCHAR(120) NOT NULL,
    admin_email VARCHAR(190) NOT NULL,
    admin_password_temp VARCHAR(255) NOT NULL,
    db_host VARCHAR(190) NOT NULL,
    db_port SMALLINT UNSIGNED NOT NULL DEFAULT 3306,
    db_name VARCHAR(190) NOT NULL,
    db_user VARCHAR(190) NOT NULL,
    db_pass VARCHAR(255) NOT NULL,
    smtp_host VARCHAR(190) DEFAULT NULL,
    smtp_port SMALLINT UNSIGNED DEFAULT NULL,
    smtp_user VARCHAR(190) DEFAULT NULL,
    smtp_pass VARCHAR(255) DEFAULT NULL,
    smtp_encryption VARCHAR(20) DEFAULT NULL,
    from_email VARCHAR(190) DEFAULT NULL,
    openai_api_key TEXT DEFAULT NULL,
    perplexity_api_key TEXT DEFAULT NULL,
    logo_path VARCHAR(255) DEFAULT NULL,
    status ENUM('draft','ready','generated','deployed','delivered') NOT NULL DEFAULT 'draft',
    zip_path VARCHAR(255) DEFAULT NULL,
    generated_at DATETIME DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_status (status),
    INDEX idx_domain (domain)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
