CREATE TABLE IF NOT EXISTS estimator_configs (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    instance_key VARCHAR(120) NOT NULL,
    city_slug VARCHAR(120) NOT NULL,
    city_name VARCHAR(120) NOT NULL,
    page_slug VARCHAR(190) NOT NULL DEFAULT 'estimation',
    mode_default ENUM('quick','advanced') NOT NULL DEFAULT 'quick',
    hero_title VARCHAR(255) NOT NULL,
    hero_subtitle TEXT NULL,
    advisor_name VARCHAR(190) NULL,
    advisor_network VARCHAR(190) NULL,
    advisor_calendar_url VARCHAR(255) NULL,
    cta_primary_label VARCHAR(120) NULL,
    cta_primary_url VARCHAR(255) NULL,
    seo_title VARCHAR(255) NULL,
    seo_description TEXT NULL,
    seo_h1 VARCHAR(255) NULL,
    public_texts_json JSON NULL,
    crm_settings_json JSON NULL,
    is_default TINYINT(1) NOT NULL DEFAULT 0,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_instance_city (instance_key, city_slug),
    INDEX idx_slug (page_slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS estimator_zones (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    config_id INT UNSIGNED NOT NULL,
    zone_code VARCHAR(80) NOT NULL,
    name VARCHAR(190) NOT NULL,
    postal_codes VARCHAR(255) NULL,
    base_price_m2 DECIMAL(12,2) NOT NULL DEFAULT 0,
    adjustment_percent DECIMAL(6,2) NOT NULL DEFAULT 0,
    sort_order INT NOT NULL DEFAULT 0,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_zone_code (config_id, zone_code),
    CONSTRAINT fk_estimator_zones_config FOREIGN KEY (config_id) REFERENCES estimator_configs(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS estimation_rules (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    config_id INT UNSIGNED NOT NULL,
    rule_name VARCHAR(190) NOT NULL,
    zone_code VARCHAR(80) NULL,
    property_type VARCHAR(60) NULL,
    condition_min ENUM('renover','correct','bon','excellent') NULL,
    condition_max ENUM('renover','correct','bon','excellent') NULL,
    min_surface DECIMAL(8,2) NULL,
    max_surface DECIMAL(8,2) NULL,
    price_per_m2 DECIMAL(12,2) NOT NULL DEFAULT 0,
    adjustment_factor DECIMAL(8,4) NOT NULL DEFAULT 0,
    priority INT NOT NULL DEFAULT 0,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_rules_config (config_id, property_type, zone_code),
    CONSTRAINT fk_estimation_rules_config FOREIGN KEY (config_id) REFERENCES estimator_configs(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS estimation_requests (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    config_id INT UNSIGNED NOT NULL,
    mode ENUM('quick','advanced') NOT NULL DEFAULT 'quick',
    city_slug VARCHAR(120) NOT NULL,
    zone_code VARCHAR(80) NULL,
    property_type VARCHAR(60) NOT NULL,
    property_address VARCHAR(255) NULL,
    surface_m2 DECIMAL(10,2) NOT NULL,
    rooms INT NULL,
    estimate_min DECIMAL(14,2) NULL,
    estimate_target DECIMAL(14,2) NULL,
    estimate_max DECIMAL(14,2) NULL,
    currency CHAR(3) NOT NULL DEFAULT 'EUR',
    bant_budget VARCHAR(120) NULL,
    bant_authority VARCHAR(120) NULL,
    bant_need VARCHAR(120) NULL,
    bant_timeline VARCHAR(120) NULL,
    contact_first_name VARCHAR(120) NULL,
    contact_last_name VARCHAR(120) NULL,
    contact_email VARCHAR(190) NOT NULL,
    contact_phone VARCHAR(40) NULL,
    advisor_name VARCHAR(190) NULL,
    advisor_network VARCHAR(190) NULL,
    appointment_enabled TINYINT(1) NOT NULL DEFAULT 0,
    appointment_slot VARCHAR(120) NULL,
    crm_status VARCHAR(120) NULL,
    status ENUM('new','qualified','appointment_booked','converted','archived') NOT NULL DEFAULT 'new',
    source_page VARCHAR(255) NULL,
    notes TEXT NULL,
    history_json JSON NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_requests_status (config_id, status, created_at),
    INDEX idx_requests_email (contact_email),
    CONSTRAINT fk_estimation_requests_config FOREIGN KEY (config_id) REFERENCES estimator_configs(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
