ALTER TABLE pages
    ADD COLUMN IF NOT EXISTS seo_score INT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS seo_title VARCHAR(160) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS seo_description VARCHAR(320) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS seo_keywords VARCHAR(255) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS seo_analyzed_at DATETIME DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS seo_issues TEXT DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS noindex TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS seo_validated TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS seo_validated_at DATETIME DEFAULT NULL;
