<?php
declare(strict_types=1);

/**
 * Métadonnées des « plugins » admin (un par dossier modules/<slug>).
 * Clés : name, description, in_sidebar, menu_group, menu_label, menu_title,
 * menu_order, icon, required_role, aliases.
 * required_role : null | 'superadmin'
 */
return [
    'dashboard' => [
        'name' => 'Tableau de bord',
        'description' => 'Vue d’ensemble de l’activité, accès rapide aux parcours et statistiques clés.',
        'in_sidebar' => true,
        'menu_group' => 'Par ici, c’est clair',
        'menu_label' => 'Vue d’ensemble',
        'menu_title' => 'Tableau de bord — votre activité en un coup d’œil',
        'menu_order' => 10,
        'icon' => 'fas fa-gauge-high',
        'required_role' => null,
        'aliases' => [],
    ],
    'commencer' => [
        'name' => 'Par où commencer',
        'description' => 'Premiers réglages, repères et enchaînement des étapes pour démarrer sereinement.',
        'in_sidebar' => true,
        'menu_group' => 'Vous avancez, étape par étape',
        'menu_label' => 'Par où commencer',
        'menu_title' => 'Démarrer : premiers réglages et repères',
        'menu_order' => 110,
        'icon' => 'fas fa-rocket',
        'required_role' => null,
        'aliases' => [],
    ],
    'positionnement' => [
        'name' => 'Votre position',
        'description' => 'Se positionner sur le marché : cible, promesse, différenciation.',
        'in_sidebar' => true,
        'menu_group' => 'Vous avancez, étape par étape',
        'menu_label' => 'Votre position',
        'menu_title' => 'Se positionner sur votre marché',
        'menu_order' => 120,
        'icon' => 'fas fa-layer-group',
        'required_role' => null,
        'aliases' => [],
    ],
    'offre' => [
        'name' => 'Ce que vous proposez',
        'description' => 'Décrire l’offre, les services et la promesse commerciale.',
        'in_sidebar' => true,
        'menu_group' => 'Vous avancez, étape par étape',
        'menu_label' => 'Ce que vous proposez',
        'menu_title' => 'Votre offre et votre promesse',
        'menu_order' => 130,
        'icon' => 'fas fa-gift',
        'required_role' => null,
        'aliases' => [],
    ],
    'attirer' => [
        'name' => 'Être trouvé',
        'description' => 'Visibilité et SEO : être trouvé par les bons prospects au bon moment.',
        'in_sidebar' => true,
        'menu_group' => 'Vous avancez, étape par étape',
        'menu_label' => 'Être trouvé',
        'menu_title' => 'Être visible : SEO et visibilité',
        'menu_order' => 140,
        'icon' => 'fas fa-magnifying-glass-chart',
        'required_role' => null,
        'aliases' => [],
    ],
    'capture' => [
        'name' => 'Attirer des demandes',
        'description' => 'Capter des contacts et des leads (formulaires, offres, conversions).',
        'in_sidebar' => true,
        'menu_group' => 'Vous avancez, étape par étape',
        'menu_label' => 'Attirer des demandes',
        'menu_title' => 'Capter des contacts et leads',
        'menu_order' => 150,
        'icon' => 'fas fa-magnet',
        'required_role' => null,
        'aliases' => ['capturer'],
    ],
    'convertir' => [
        'name' => 'Conclure',
        'description' => 'Process de vente, rendez-vous, arguments et clôture (conversion).',
        'in_sidebar' => true,
        'menu_group' => 'Vous avancez, étape par étape',
        'menu_label' => 'Conclure',
        'menu_title' => 'Signer des clients, conversion',
        'menu_order' => 160,
        'icon' => 'fas fa-arrow-trend-up',
        'required_role' => null,
        'aliases' => [],
    ],
    'optimiser' => [
        'name' => 'Faire mieux',
        'description' => 'Analytics, A/B, rapports : améliorer le pilotage des performances.',
        'in_sidebar' => true,
        'menu_group' => 'Vous avancez, étape par étape',
        'menu_label' => 'Faire mieux',
        'menu_title' => 'Améliorer vos résultats',
        'menu_order' => 170,
        'icon' => 'fas fa-chart-line',
        'required_role' => null,
        'aliases' => [],
    ],
    'cms-hub' => [
        'name' => 'Pages & contenus',
        'description' => 'Contenu, pages structurantes et textes du site public.',
        'in_sidebar' => true,
        'menu_group' => 'Votre site, vos textes',
        'menu_label' => 'Pages & contenus',
        'menu_title' => 'Contenu et pages du site',
        'menu_order' => 210,
        'icon' => 'fas fa-file-lines',
        'required_role' => null,
        'aliases' => [],
    ],
    'crm-hub' => [
        'name' => 'Contacts & suivi',
        'description' => 'Vue CRM : leads, suivi, statuts et historique d’échanges.',
        'in_sidebar' => true,
        'menu_group' => 'Vos contacts & suivi',
        'menu_label' => 'Contacts & suivi',
        'menu_title' => 'CRM et contacts',
        'menu_order' => 310,
        'icon' => 'fas fa-address-book',
        'required_role' => null,
        'aliases' => [],
    ],
    'marketing-hub' => [
        'name' => 'Marketing & relances',
        'description' => 'Relances, automations et actions marketing ciblées.',
        'in_sidebar' => true,
        'menu_group' => 'Relances & visibilité',
        'menu_label' => 'Marketing & relances',
        'menu_title' => 'Marketing et automatisations',
        'menu_order' => 410,
        'icon' => 'fas fa-bolt',
        'required_role' => null,
        'aliases' => [],
    ],
    'properties-hub' => [
        'name' => 'Annonces & secteurs',
        'description' => 'Mandats, annonces, secteurs et cadrage offre / zones.',
        'in_sidebar' => true,
        'menu_group' => 'Biens, secteurs, local',
        'menu_label' => 'Annonces & secteurs',
        'menu_title' => 'Propriétés et secteurs',
        'menu_order' => 510,
        'icon' => 'fas fa-house',
        'required_role' => null,
        'aliases' => [],
    ],
    'annuaire-local' => [
        'name' => 'Annuaire local',
        'description' => 'Fiches locales, partenaires et présence de proximité.',
        'in_sidebar' => true,
        'menu_group' => 'Biens, secteurs, local',
        'menu_label' => 'Annuaire local',
        'menu_title' => 'Fiches et annuaire local',
        'menu_order' => 520,
        'icon' => 'fas fa-store',
        'required_role' => null,
        'aliases' => [],
    ],
    'outils-hub' => [
        'name' => 'Outils & exports',
        'description' => 'Outils, téléchargements, scripts et ressources opérationnelles.',
        'in_sidebar' => true,
        'menu_group' => 'Boîte à outils',
        'menu_label' => 'Outils & exports',
        'menu_title' => 'Boîte à outils : téléchargements, scripts, ressources',
        'menu_order' => 610,
        'icon' => 'fas fa-toolbox',
        'required_role' => null,
        'aliases' => [],
    ],
    'checklist' => [
        'name' => 'Checklist client',
        'description' => 'Listes de vérification partageables avec le client (lancement, conformité, etc.).',
        'in_sidebar' => true,
        'menu_group' => 'Boîte à outils',
        'menu_label' => 'Checklist client',
        'menu_title' => 'Checklist de verification partageable avec le client',
        'menu_order' => 620,
        'icon' => 'fas fa-list-check',
        'required_role' => null,
        'aliases' => [],
    ],
    'profil' => [
        'name' => 'Mon profil',
        'description' => 'Identité pro, contact affiché et personnalisation du compte.',
        'in_sidebar' => true,
        'menu_group' => 'Votre compte',
        'menu_label' => 'Mon profil',
        'menu_title' => 'Profil et identité',
        'menu_order' => 710,
        'icon' => 'fas fa-user-gear',
        'required_role' => null,
        'aliases' => [],
    ],
    'site' => [
        'name' => 'Site public',
        'description' => 'Aperçu et paramètres liés au site vitrine côté public.',
        'in_sidebar' => true,
        'menu_group' => 'Votre compte',
        'menu_label' => 'Site public',
        'menu_title' => 'Aperçu et réglages du site public',
        'menu_order' => 720,
        'icon' => 'fas fa-globe',
        'required_role' => null,
        'aliases' => [],
    ],
    'parametres' => [
        'name' => 'Paramètres',
        'description' => 'Paramètres techniques, messagerie, intégrations et options avancées.',
        'in_sidebar' => true,
        'menu_group' => 'Votre compte',
        'menu_label' => 'Paramètres',
        'menu_title' => 'Paramètres techniques et messagerie',
        'menu_order' => 730,
        'icon' => 'fas fa-gear',
        'required_role' => null,
        'aliases' => [],
    ],
    'superadmin' => [
        'name' => 'Superadmin',
        'description' => 'Outils d’administration avancés et accès directs (réservé).',
        'in_sidebar' => true,
        'menu_group' => 'Votre compte',
        'menu_label' => 'Superadmin',
        'menu_title' => 'Superadmin — modules et accès en direct',
        'menu_order' => 740,
        'icon' => 'fas fa-crown',
        'required_role' => 'superadmin',
        'aliases' => [],
    ],
    'agents' => [
        'name' => 'Agents IA',
        'description' => 'Configuration des agents d’intelligence artificielle et automatisations associées.',
        'in_sidebar' => false,
        'menu_group' => null,
        'menu_label' => null,
        'required_role' => null,
        'aliases' => [],
    ],
    'aide' => [
        'name' => 'Aide & documentation',
        'description' => 'Centre d’aide, vidéos et ressources pour utiliser l’espace client.',
        'in_sidebar' => false,
        'menu_group' => null,
        'menu_label' => null,
        'required_role' => null,
        'aliases' => [],
    ],
    'ai-help-chat' => [
        'name' => 'Chat d’aide IA',
        'description' => 'Assistance par conversation (réponses et guidage contextuel).',
        'in_sidebar' => false,
        'menu_group' => null,
        'menu_label' => null,
        'required_role' => null,
        'aliases' => [],
    ],
    'api-keys' => [
        'name' => 'Clés API',
        'description' => 'Gestion des clés d’API pour services externes (LLM, outils, etc.).',
        'in_sidebar' => false,
        'menu_group' => null,
        'menu_label' => null,
        'required_role' => null,
        'aliases' => [],
    ],
    'biens' => [
        'name' => 'Biens',
        'description' => 'Liste et gestion des annonces / biens (back-office).',
        'in_sidebar' => false,
        'menu_group' => null,
        'menu_label' => null,
        'required_role' => null,
        'aliases' => [],
    ],
    'blog' => [
        'name' => 'Blog & articles',
        'description' => 'Gestion des articles, catégories et publication du blog.',
        'in_sidebar' => false,
        'menu_group' => null,
        'menu_label' => null,
        'required_role' => null,
        'aliases' => [],
    ],
    'cms' => [
        'name' => 'CMS (pages)',
        'description' => 'Gestion de pages type CMS (hors hub regroupé).',
        'in_sidebar' => false,
        'menu_group' => null,
        'menu_label' => null,
        'required_role' => null,
        'aliases' => [],
    ],
    'capturer' => [
        'name' => 'Leads (vue CRM)',
        'description' => 'File de leads rattachée à la phase de capture (vue altern.).',
        'in_sidebar' => false,
        'menu_group' => null,
        'menu_label' => null,
        'required_role' => null,
        'aliases' => [],
    ],
    'construire' => [
        'name' => 'Construire',
        'description' => 'Fondations marketing, persona et système d’acquisition (parcours « Construire »).',
        'in_sidebar' => false,
        'menu_group' => null,
        'menu_label' => null,
        'required_role' => null,
        'aliases' => [],
    ],
    'contacts' => [
        'name' => 'Contacts & leads (détail)',
        'description' => 'Détail des contacts et piste de traitement (hors hub).',
        'in_sidebar' => false,
        'menu_group' => null,
        'menu_label' => null,
        'required_role' => null,
        'aliases' => [],
    ],
    'email-sequences' => [
        'name' => 'Séquences e-mail',
        'description' => 'Séquences d’e-mails automatisées (scénarios, étapes, envois).',
        'in_sidebar' => false,
        'menu_group' => null,
        'menu_label' => null,
        'required_role' => null,
        'aliases' => [],
    ],
    'estimation' => [
        'name' => 'Estimation (tunnel)',
        'description' => 'Outils d’estimation immobilière et tunnel associé côté admin.',
        'in_sidebar' => false,
        'menu_group' => null,
        'menu_label' => null,
        'required_role' => null,
        'aliases' => [],
    ],
    'estimation_dvf' => [
        'name' => 'Estimation DVF (admin)',
        'description' => 'Pilote des données DVF et demandes d’estimation côté opérationnel.',
        'in_sidebar' => false,
        'menu_group' => null,
        'menu_label' => null,
        'required_role' => null,
        'aliases' => [],
    ],
    'financement' => [
        'name' => 'Financement (demandes)',
        'description' => 'Traitement des demandes de prêt / financement reçues via le site.',
        'in_sidebar' => false,
        'menu_group' => null,
        'menu_label' => null,
        'required_role' => null,
        'aliases' => [],
    ],
    'funnels' => [
        'name' => 'Entonnoirs (funnels)',
        'description' => 'Pipelines, tunnels de conversion et scénarios multi-étapes.',
        'in_sidebar' => false,
        'menu_group' => null,
        'menu_label' => null,
        'required_role' => null,
        'aliases' => [],
    ],
    'generateur-contenu' => [
        'name' => 'Générateur de contenu',
        'description' => 'Aide à la rédaction et génération de contenus (textes, fiches, etc.).',
        'in_sidebar' => false,
        'menu_group' => null,
        'menu_label' => null,
        'required_role' => null,
        'aliases' => [],
    ],
    'gmb' => [
        'name' => 'Google My Business',
        'description' => 'Fiche Google Business Profile et cohérence d’adresse / avis / posts.',
        'in_sidebar' => true,
        'menu_group' => 'Trouver des clients',
        'menu_label' => 'Google My Business',
        'menu_title' => 'Fiche GMB, avis et statistiques locales',
        'menu_order' => 30,
        'icon' => 'fas fa-store',
        'required_role' => null,
        'aliases' => [],
    ],
    'ia-config' => [
        'name' => 'Configuration IA',
        'description' => 'Fournisseurs, modèles et réglages des fonctionnalités IA du site.',
        'in_sidebar' => false,
        'menu_group' => null,
        'menu_label' => null,
        'required_role' => null,
        'aliases' => [],
    ],
    'landing-pages' => [
        'name' => 'Landing pages (ads)',
        'description' => 'Pages d’atterrissage publicitaires et liens de campagne (UTM, tracking).',
        'in_sidebar' => false,
        'menu_group' => null,
        'menu_label' => null,
        'required_role' => null,
        'aliases' => [],
    ],
    'listings' => [
        'name' => 'Listings (flux)',
        'description' => 'Gestion de flux et formats d’annonces (synchronisation / exports).',
        'in_sidebar' => false,
        'menu_group' => null,
        'menu_label' => null,
        'required_role' => null,
        'aliases' => [],
    ],
    'messagerie' => [
        'name' => 'Messagerie',
        'description' => 'Messages entrants / sortants, boîte de réception pro.',
        'in_sidebar' => false,
        'menu_group' => null,
        'menu_label' => null,
        'required_role' => null,
        'aliases' => [],
    ],
    'newsletter' => [
        'name' => 'Newsletter',
        'description' => 'Inscriptions, envois et veille sur l’e-mail de masse (news).',
        'in_sidebar' => false,
        'menu_group' => null,
        'menu_label' => null,
        'required_role' => null,
        'aliases' => [],
    ],
    'redaction' => [
        'name' => 'Rédaction',
        'description' => 'Brouillons, fiches de style et atelier rédactionnel.',
        'in_sidebar' => false,
        'menu_group' => null,
        'menu_label' => null,
        'required_role' => null,
        'aliases' => [],
    ],
    'scraper' => [
        'name' => 'Scraper (web)',
        'description' => 'Outils d’extraction de données sur le web (crawl / parsing).',
        'in_sidebar' => false,
        'menu_group' => null,
        'menu_label' => null,
        'required_role' => null,
        'aliases' => [],
    ],
    'scraping' => [
        'name' => 'Scraping (eXp / flux)',
        'description' => 'Pipelines de scraping dédiés (eXp France, imports structurés).',
        'in_sidebar' => false,
        'menu_group' => null,
        'menu_label' => null,
        'required_role' => null,
        'aliases' => [],
    ],
    'secteurs' => [
        'name' => 'Secteurs & zones',
        'description' => 'Cartographie des secteurs, villes, quartiers et contenus de zone.',
        'in_sidebar' => false,
        'menu_group' => null,
        'menu_label' => null,
        'required_role' => null,
        'aliases' => [],
    ],
    'seo' => [
        'name' => 'SEO (détaillé)',
        'description' => 'Ecran SEO avancé (hors attirer) : mots-clés, structure, outils de pilotage.',
        'in_sidebar' => false,
        'menu_group' => null,
        'menu_label' => null,
        'required_role' => null,
        'aliases' => [],
    ],
    'social' => [
        'name' => 'Réseaux sociaux',
        'description' => 'Réseaux sociaux, posts et liens de diffusion.',
        'in_sidebar' => false,
        'menu_group' => null,
        'menu_label' => null,
        'required_role' => null,
        'aliases' => [],
    ],
    'telecharger' => [
        'name' => 'Téléchargements',
        'description' => 'Fichiers et ressources à mettre à disposition des visiteurs ou de l’équipe.',
        'in_sidebar' => false,
        'menu_group' => null,
        'menu_label' => null,
        'required_role' => null,
        'aliases' => [],
    ],
    'telegram' => [
        'name' => 'Bot Telegram',
        'description' => 'Intégration du bot Telegram (webhooks, notifications, commandes).',
        'in_sidebar' => false,
        'menu_group' => null,
        'menu_label' => null,
        'required_role' => null,
        'aliases' => [],
    ],
    'gmb-scraper' => [
        'name' => 'Scraper fiche Google',
        'description' => 'Extraire nom, adresse et indices visibles depuis un lien Google Maps pour préremplir la fiche GMB locale.',
        'in_sidebar' => true,
        'menu_group' => 'Trouver des clients',
        'menu_label' => 'Scraper fiche Google',
        'menu_title' => 'Importer les infos visibles depuis Google Maps vers votre fiche locale',
        'menu_order' => 20,
        'icon' => 'fas fa-map-location-dot',
        'required_role' => null,
        'aliases' => [],
    ],
];
